### ISSUE TITLE
Parse/Render String

### ISSUE THREAD

**Issue by TylorS** [jsx-ir/jsx-to-idom#1]
I'm not sure if this issue should be here or jsx-runtime.
I'm trying to use this plugin to render a file I request from my server but it comes back as a string.
This would be very helpful.

**Comment by NekR** [comment]
You probably should execute that file since JSX is just JavaScript and then get reference to the function or JSX object you are using. For example if you have this:

``` javascript
export default function view() {
  return <div>...</div>
}
```

Then you need to execute that script and pass exported function to the render function, e.g. this:

``` javascript
import view from './myViewFile.jsx'
render(view);
```

I understand that you are downloading it from the server, maybe you should use some modules loaded like AMD to achieve same effect or just JSONP.
